spring.application.name=socialmedx
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/socialMedX
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=5555555512314123123
jwt.expiration=86400000